services:
    wolfsblvt.highlightunreadposts.listener:
        class: wolfsblvt\highlightunreadposts\event\listener
        arguments:
            - @dbal.conn
            - @config
            - @path_helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
