services:
    wolfsblvt.highlightunreadposts.listener:
        class: wolfsblvt\highlightunreadposts\event\listener
        arguments:
            - @config
            - @template
        tags:
            - { name: event.listener }
